-- 샘플 테이블 DDL (로컬 Oracle XE 환경에서 실행)
-- containers/ 디렉토리의 Docker 환경 기준 (username: generator)

CREATE TABLE SAMPLE_USER (
    USER_ID       NUMBER(19)    NOT NULL,
    USER_NAME     VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(200) NOT NULL,
    PHONE         VARCHAR2(20),
    STATUS        VARCHAR2(10)  DEFAULT 'ACTIVE',
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT    TIMESTAMP,
    CONSTRAINT PK_SAMPLE_USER PRIMARY KEY (USER_ID)
);

CREATE TABLE SAMPLE_ORDER (
    ORDER_ID      NUMBER(19)    NOT NULL,
    USER_ID       NUMBER(19)    NOT NULL,
    ORDER_NAME    VARCHAR2(200) NOT NULL,
    AMOUNT        NUMBER(15,2)  DEFAULT 0,
    STATUS        VARCHAR2(20)  DEFAULT 'PENDING',
    ORDERED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_SAMPLE_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES SAMPLE_USER(USER_ID)
);
